const defaultConfig = require( '@wordpress/scripts/config/webpack.config' );
const path = require( 'path' );
const webpack = require( 'webpack' );

/**
 * Source-link banner for the generated (minified) JS.
 *
 * CartBay ships minified JS but bundles no third-party libraries: its scripts
 * are vanilla JS, and @wordpress/* imports are externalized to window.wp.* by
 * @wordpress/scripts (see the generated *.asset.php). So there is nothing to
 * attribute in a *.LICENSE.txt — we intentionally do NOT generate one. If a
 * licensed dependency is ever bundled, @wordpress/scripts' default Terser
 * extractComments will emit the *.LICENSE.txt automatically.
 *
 * The banner points reviewers/users to the human-readable source, per
 * WordPress.org guideline #3 ("code must be (mostly) human readable"). The URL
 * is derived from package.json "repository".
 */
const packageJson = require( './package.json' );

let repoUrl = '';
if ( packageJson.repository ) {
	repoUrl =
		typeof packageJson.repository === 'string'
			? packageJson.repository
			: packageJson.repository.url || '';
	repoUrl = repoUrl.replace( /^git\+/, '' ).replace( /\.git$/, '' );
}
const version = packageJson.version || '1.0.0';

const bannerText = `/*!
 * CartBay - Abandoned Cart Recovery for WooCommerce
 * Copyright (c) ${ new Date().getFullYear() } WP Anchor Bay - https://wpanchorbay.com
 *
 * This software is licensed under the GPLv2 or later.
 * This file is generated from un-compiled source code. Do not edit this file directly.
 *
 * Source Code: ${ repoUrl }/tree/v${ version }/
 * Source (src): ${ repoUrl }/tree/v${ version }/src
 */`;

/**
 * Prepend the banner AFTER minification so Terser cannot strip or extract it
 * (a webpack.BannerPlugin banner runs before minify and would be consumed).
 */
class SourceBannerPlugin {
	apply( compiler ) {
		compiler.hooks.thisCompilation.tap( 'SourceBannerPlugin', ( compilation ) => {
			compilation.hooks.processAssets.tap(
				{
					name: 'SourceBannerPlugin',
					// Late stage: after code splitting and minification.
					stage: webpack.Compilation.PROCESS_ASSETS_STAGE_REPORT,
				},
				( assets ) => {
					compilation.entrypoints.forEach( ( entrypoint ) => {
						entrypoint.getFiles().forEach( ( file ) => {
							if ( file.endsWith( '.js' ) && assets[ file ] ) {
								compilation.updateAsset(
									file,
									new webpack.sources.ConcatSource(
										bannerText,
										'\n',
										assets[ file ]
									)
								);
							}
						} );
					} );
				}
			);
		} );
	}
}

module.exports = {
	...defaultConfig,
	entry: {
		'cartbay-capture': path.resolve( __dirname, 'src/capture/index.js' ),
		'cartbay-block': path.resolve( __dirname, 'src/block/index.js' ),
	},
	output: {
		...defaultConfig.output,
		path: path.resolve( __dirname, 'assets/js' ),
	},
	plugins: [ ...( defaultConfig.plugins || [] ), new SourceBannerPlugin() ],
};
